config/routes.rb
Rails.application.routes.draw do
  resources :user_areas
  resources :services
  resources :service_requests do
    collection do
      post :areas
      post :subareas
      match :services_area, via: [:get, :post]
      get :answer_request
      get :schedule_request
      get :forward_responsible
      post :save_forward_responsible
      post :save_schedule_request
      post :save_answer_service
    end
  end
  post 'services_area' => 'service_requests#services_area'
  post 'download_file' => 'service_requests#download_file'

  resources :units
  resources :areas
  get 'dashboard/index'
  # patch "process_managers/update" => "process_managers#update", :as => "process_managers/update"
  resources :process_managers do
    collection do
      post :search_process
  	end
  end
  devise_for :users, controllers: { sessions: 'users/sessions' }
  get 'home/index'
  root to: 'dashboard#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
	has_many :user_areas
	belongs_to :unit
end

app/models/priority.rb
class Priority < ApplicationRecord
end

app/models/process_manager.rb
class ProcessManager < ApplicationRecord
	validates :process_number, :opening_hour_date, :subject, :notes, :confidentiality_level, :priority, :authors, presence: true
end

app/models/service.rb
class Service < ApplicationRecord
	has_many :service_requests
end

app/models/service_file.rb
class ServiceFile < ApplicationRecord

	def self.upload_file(files, directory)
		FileUtils.mkdir(directory) unless File.exists?(directory)
		if !files.nil?
			files.each do |file|
				File.open(File.join(directory, file.original_filename), 'wb') { |f| f.write(file.read) }
			end
		end
	end

	def self.download_file(directory)
		send_file directory
	end

	def self.list_service_files(service_id)
		directory = ServiceRequest.find(service_id).files_directory
		if !directory.nil?
			files = Dir.foreach(directory).map { |f| File.basename("#{f}") }.tap { |x| x.delete(".."); x.delete("."); }
		end
	end

end

app/models/service_request.rb
class ServiceRequest < ApplicationRecord
  belongs_to :unit, required: false
  belongs_to :status, required: false
  belongs_to :service
end

app/models/status.rb
class Status < ApplicationRecord
end

app/models/unit.rb
class Unit < ApplicationRecord
	has_many :areas
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true
  has_many :user_areas
  has_many :areas, through: :user_areas
end

app/models/user_area.rb
class UserArea < ApplicationRecord
  belongs_to :user
  belongs_to :area
end

app/models/viproc_information.rb
class ViprocInformation < ApplicationRecord
	require 'savon'

	HOMOLOGACAO = 'http://viprocwsejb-h.seplag.ce.gov.br/viprocws/ViprocService?wsdl'
	# PRODUCAO = 'http://viprocwsejb.seplag.ce.gov.br/viprocws/ViprocService?wsdl'

	CLIENT = Savon.client(element_form_default: :unspecified, wsdl: HOMOLOGACAO)

	def self.criar_processo(parametros)
		CLIENT.call(:criar_processo, message: parametros)
	end

	def self.listar_assuntos
		CLIENT.call(:listar_assuntos).body[:listar_assuntos_response][:return].sort
	end

	def self.listar_sigla_orgaos
		CLIENT.call(:listar_sigla_orgaos).body[:listar_sigla_orgaos_response][:return].sort
	end

	def self.listar_sigla_lotacoes
		CLIENT.call(:listar_sigla_lotacoes)
	end

end

app/models/viproc_profile.rb
class ViprocProfile < ApplicationRecord
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url, notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:name, :active)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@process_manager = ProcessManager.new
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :sla_service_hour, :sla_service_minute, :function_id, :active)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/user_areas_helper.rb
module UserAreasHelper
end

app/views/services/_form.html.erb
<%= form_with(model: service, local: true) do |form| %>
  <% if service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :service_name %>
  </div>

  <div class="field">
    <%= form.label :sla_service_hour %>
    <%= form.number_field :sla_service_hour, id: :service_sla_service_hour %>
  </div>

  <div class="field">
    <%= form.label :sla_service_minute %>
    <%= form.number_field :sla_service_minute, id: :service_sla_service_minute %>
  </div>

  <div class="field">
    <%= form.label :function_id %>
    <%= form.number_field :function_id, id: :service_function_id %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active, id: :service_active %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Services</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Sla service hour</th>
      <th>Sla service minute</th>
      <th>Function</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.name %></td>
        <td><%= service.sla_service_hour %></td>
        <td><%= service.sla_service_minute %></td>
        <td><%= service.function_id %></td>
        <td><%= service.active %></td>
        <td><%= link_to 'Show', service %></td>
        <td><%= link_to 'Edit', edit_service_path(service) %></td>
        <td><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service', new_service_path %>

app/views/services/new.html.erb
<h1>New Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @service.name %>
</p>

<p>
  <strong>Sla service hour:</strong>
  <%= @service.sla_service_hour %>
</p>

<p>
  <strong>Sla service minute:</strong>
  <%= @service.sla_service_minute %>
</p>

<p>
  <strong>Function:</strong>
  <%= @service.function_id %>
</p>

<p>
  <strong>Active:</strong>
  <%= @service.active %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>