config/routes.rb
Rails.application.routes.draw do
  resources :user_areas
  resources :services
  resources :service_requests do
    collection do
      post :areas
      post :subareas
      match :services_area, via: [:get, :post]
      get :answer_request
      get :schedule_request
      get :forward_responsible
      post :save_forward_responsible
      post :save_schedule_request
      post :save_answer_service
    end
  end
  post 'services_area' => 'service_requests#services_area'
  post 'download_file' => 'service_requests#download_file'

  resources :units
  resources :areas
  get 'dashboard/index'
  # patch "process_managers/update" => "process_managers#update", :as => "process_managers/update"
  resources :process_managers do
    collection do
      post :search_process
  	end
  end
  devise_for :users, controllers: { sessions: 'users/sessions' }
  get 'home/index'
  root to: 'dashboard#index'
end

app/models/service_request.rb
class ServiceRequest < ApplicationRecord
  belongs_to :unit, required: false
  belongs_to :status, required: false
  belongs_to :service
end

app/controllers/service_requests_controller.rb
class ServiceRequestsController < ApplicationController
  before_action :set_service_request, only: [:show, :edit, :update, :destroy]

  # GET /service_requests
  # GET /service_requests.json
  def index
    @service_requests_area = ServiceRequest.all.order('date_request DESC, time_request DESC').where("requested_area = 1 and user_responsible_attendance is null").page(params[:page])
    @service_requests_attend = ServiceRequest.all.order('date_request DESC, time_request DESC').where("date_service is null and user_responsible_attendance = #{current_user.id}").page(params[:page])
    @service_requests_attended = ServiceRequest.all.order('date_request DESC, time_request DESC').where("date_service is not null and user_responsible_attendance = #{current_user.id}").page(params[:page]).per(18)
    @service_requests_requested = ServiceRequest.all.order('date_request DESC, time_request DESC').where("user_requesting = #{current_user.id}").page(params[:page]).per(18)
  end

  # GET /service_requests/1
  # GET /service_requests/1.json
  def show
    @list_service_files = ServiceFile.list_service_files(params[:id])
  end

  # GET /service_requests/new
  def new
    @area_requesting = UserArea.find_by(user_id: current_user.id)&.area
    @service_request = ServiceRequest.new
  end

  # GET /service_requests/1/edit
  def edit
  end

  # POST /service_requests
  # POST /service_requests.json
  def create
    @service_request = ServiceRequest.new(service_request_params)

    respond_to do |format|
      if @service_request.save
        @service_request.update_attributes(files_directory: "#{Rails.root}/service_files/#{@service_request.id}")
        directory = @service_request.files_directory
        files = params[:files_directory]
        ServiceFile.upload_file(files, directory)
        format.html { redirect_to @service_request, notice: 'Service request was successfully created.' }
        format.json { render :show, status: :created, location: @service_request }
      else
        format.html { render :new }
        format.json { render json: @service_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /service_requests/1
  # PATCH/PUT /service_requests/1.json
  def update
    respond_to do |format|
      if @service_request.update(service_request_params)
        format.html { redirect_to @service_request, notice: 'Service request was successfully updated.' }
        format.json { render :show, status: :ok, location: @service_request }
      else
        format.html { render :edit }
        format.json { render json: @service_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_requests/1
  # DELETE /service_requests/1.json
  def destroy
    @service_request.destroy
    respond_to do |format|
      format.html { redirect_to service_requests_url, notice: 'Service request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def areas
    @areas = Area.where("unit_id = #{params[:unit_id]} and area_id is null")
  end

  def services_area
    @services_area = Service.where(area_id: params[:area_id])
  end

  def schedule_request
    @service_request = ServiceRequest.find(params[:service_request_id])
  end

  def save_schedule_request
    @service_request = ServiceRequest.find(params[:service_request_id])
    @service_request.update_attributes(date_scheduled: params[:date_scheduled], time_scheduled: params[:time_scheduled])
    @service_request.save

    redirect_to action: :index
  end

  def answer_request
    @service_request_id = params[:service_request_id]
  end

  def save_answer_service
    @service_request = ServiceRequest.find(params[:service_request_id])
    @service_request.update_attributes(user_responsible_attendance: params[:user_responsible_attendance], date_service: params[:date_service], time_service: params[:time_service], status_id: params[:status], notes: params[:notes])
    @service_request.save

    redirect_to action: :index
  end

  def forward_responsible
    @service_request_id = params[:service_request_id]
  end

  def save_forward_responsible
    @service_request = ServiceRequest.find(params[:service_request_id]).update_attributes(user_responsible_attendance: params[:user_responsible_attendance])
    
    redirect_to action: :index
  end

  def download_file
    directory = "#{ServiceRequest.find(params[:id]).files_directory}/" + "#{params[:filename]}"
    send_file(directory)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_request
      @service_request = ServiceRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_request_params
      params.require(:service_request).permit(:date_request, :time_request, :description_problem, :service_id, :maximum_time_of_attendance, :unit_id, :area_requesting, :subarea_requesting, :user_requesting, :user, :date_response, :time_response, :user_responsible_attendance, :date_scheduled, :time_scheduled, :date_service, :time_service, :time_finalization_attendance, :notes, :status_id, :requested_area, :files_directory, :service_number)
    end
end

app/helpers/service_requests_helper.rb
module ServiceRequestsHelper
end

app/views/service_requests/_area.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>Data/Hora da Solicitação</th>
      <th>Serviço Solicitado</th>
      <th>Descrição do Serviço</th>
      <th>Unidade Socioeducativa</th>
      <th>Área Solicitante</th>
      <th>Usuário Solicitante</th>
      <th>Atendimento para</th>
      <th colspan="3">Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @service_requests_area.each do |service_request| %>
      <tr>
        <td><%= service_request.date_request.strftime('%d/%m/%Y') + ' ' + service_request.time_request.strftime('%H:%M') %></td>
        <td><%= service_request.service&.name %></td>
        <td><%= service_request.description_problem %></td>
        <td><%= Area.find(service_request.area_requesting)&.unit&.name %></td>
        <td><%= Area.find(service_request.area_requesting).name if !service_request.area_requesting.blank? %></td>
        <td><%= User.find(service_request.user_requesting).name if !service_request.user_requesting.blank? %></td>
        <td><%= User.find(service_request.service_for)&.name if !service_request.service_for.blank? %></td>
        <td><%= link_to '<i class="fa fa-list-alt" aria-hidden="true" title="Detalhes do serviço."></i>'.html_safe, service_request_path(service_request.id) %></td>
        <td><%= link_to '<i class="fa fa-users" aria-hidden="true" title="Encaminhar para responsável."></i>'.html_safe, forward_responsible_service_requests_path(service_request_id: service_request.id), remote: true %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="text-center">
  <%= paginate @service_requests_area %>
</div>

<!-- <div id="div_schedule_request"></div>
<div id="div_answer_service"></div> -->

<div id="div_forward_responsible"></div>

app/views/service_requests/_attend.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>Data/Hora da Solicitação</th>
      <th>Serviço Solicitado</th>
      <th>Descrição do Serviço</th>
      <th>Unidade Socioeducativa</th>
      <th>Área Solicitante</th>
      <th>Usuário Solicitante</th>
      <th>Atendimento para</th>
      <th colspan="3">Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @service_requests_attend.each do |service_request| %>
      <tr>
        <td><%= service_request.date_request.strftime('%d/%m/%Y') + ' ' + service_request.time_request.strftime('%H:%M') %></td>
        <td><%= service_request.service&.name %></td>
        <td><%= service_request.description_problem %></td>
        <td><%= Area.find(service_request.area_requesting)&.unit&.name %></td>
        <td><%= Area.find(service_request.area_requesting).name if !service_request.area_requesting.blank? %></td>
        <td><%= User.find(service_request.user_requesting).name if !service_request.user_requesting.blank? %></td>
        <td><%= User.find(service_request.service_for)&.name if !service_request.service_for.blank? %></td>
        <td><%= link_to '<i class="fa fa-list-alt" aria-hidden="true" title="Detalhes do serviço."></i>'.html_safe, service_request_path(service_request.id) %></td>
        <% if !service_request.date_scheduled.nil? %>
          <td><%= link_to '<i class="fa fa-calendar-check-o" aria-hidden="true" title="Programar data para atendimento do serviço."></i>'.html_safe, schedule_request_service_requests_path(service_request_id: service_request.id), remote: true %></td>
        <% else %>
          <td><%= link_to '<i class="fa fa-calendar-o" aria-hidden="true" title="Programar data para atendimento do serviço."></i>'.html_safe, schedule_request_service_requests_path(service_request_id: service_request.id), remote: true %></td>
        <% end %>
        <td><%= link_to '<i class="fa fa-paper-plane" aria-hidden="true" title="Atender o serviço."></i>'.html_safe, answer_request_service_requests_path(service_request_id: service_request.id), remote: true %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="text-center">
  <%= paginate @service_requests_attend %>
</div>

<div id="div_schedule_request"></div>
<div id="div_answer_service"></div>

app/views/service_requests/_attended.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>Data/Hora da Solicitação</th>
      <th>Serviço Solicitado</th>
      <th>Descrição do Serviço</th>
      <th>Unidade Socioeducativa</th>
      <th>Área Solicitante</th>
      <th>Usuário Solicitante</th>
      <th>Atendimento para</th>
      <th colspan="3">Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @service_requests_attended.each do |service_request| %>
      <tr>
        <td><%= service_request.date_request.strftime('%d/%m/%Y') + ' ' + service_request.time_request.strftime('%H:%M') %></td>
        <td><%= service_request.service&.name %></td>
        <td><%= service_request.description_problem %></td>
        <td><%= Area.find(service_request.area_requesting)&.unit&.name %></td>
        <td><%= Area.find(service_request.area_requesting).name if !service_request.area_requesting.blank? %></td>
        <td><%= User.find(service_request.user_requesting).name if !service_request.user_requesting.blank? %></td>
        <td><%= User.find(service_request.service_for)&.name if !service_request.service_for.blank? %></td>
        <td><%= link_to '<i class="fa fa-list-alt" aria-hidden="true" title="Detalhes do serviço."></i>'.html_safe, service_request_path(service_request.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="text-center">
  <%= paginate @service_requests_attended %>
</div>

app/views/service_requests/_form.html.erb
<%= form_with(model: service_request, local: true, :multipart => true) do |form| %>
  <% if service_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service_request.errors.count, "error") %> prohibited this service_request from being saved:</h2>

      <ul>
      <% service_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :date_request, value: Date.current, id: :service_request_date_request %>

  <%= form.hidden_field :time_request, value: Time.current, id: :service_request_time_request %>

  <%= form.hidden_field :user_requesting, value: current_user.id, id: :service_request_user_requesting %>

  <%= form.hidden_field :area_requesting, value: @area_requesting&.id, id: :service_request_area_requesting %>


  <div class="row">
    <div class="col-md-6">
      <%= form.label :unit, 'Unidade' %>
      <%= form.collection_select :unit, Unit.all, :id, :name, {prompt: 'Selecione'}, class: 'form-control select2', required: true, id: :unit %>
    </div>

    <div class="col-md-6">
      <%= form.label :requested_area %>
      <%= form.select :requested_area, [], {prompt: 'Selecione'}, {data: {remote: true, url: services_area_path}, class: 'form-control select2', required: true, id: :area} %>
    </div>
  </div>
  <br>

  <div class="row">
    <div class="col-md-12">
      <%= form.label :service_id %>
      <%= form.select :service_id, [], {prompt: 'Selecione'}, id: :service, class: 'form-control select2', required: true %>
    </div>
  </div>
  <br>

  <div class="row">
    <div class="col-md-12">
      <%= form.label :description_problem %>
      <%= form.text_area :description_problem, id: :service_request_description_problem, class: 'form-control', required: true %>
    </div>
  </div>
  <br>

  <div class="row">
    <div class="col-md-4">
      <label>
        <input id="new-user" type="checkbox"> Atendimento para outro usuário
      </label>
    </div>

    <div id="service_request_user" class="col-md-8">
      <%= form.label :service_for %>
      <%= form.collection_select :service_for, User.all, :id, :name, {prompt: 'Selecione'}, id: :service_request_user, class: 'form-control' %>
    </div>
  </div>
  <br>

  <div class="row">
    <div class="col-md-4">
      <%= file_field_tag "files_directory[]", multiple: true %>
    </div>
  </div>
  <br>

  <div class="actions">
    <%= form.submit 'Solicitar', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/service_requests/_modal_schedule_request.html.erb
<div class="modal fade" id="modalSchedule" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Programar data para atendimento do serviço</h4>
      </div>
      <div class="modal-body">
        <%= form_tag('/service_requests/save_schedule_request') do %>
          <%= hidden_field_tag :service_request_id, @service_request.id %>
          <div class="row">
            <div class="col-md-6">
              <label>Dada Programada</label>
              <%= text_field_tag :date_scheduled, (@service_request.date_scheduled&.strftime('%d/%m/%Y') || Date.current.strftime('%d/%m/%Y')), class: 'form-control mask_date', required: true %>
            </div>

            <div class="col-md-6">
              <label>Hora Programada</label>
              <%= text_field_tag :time_scheduled, (@service_request.time_scheduled&.strftime('%H:%M') || Time.current.strftime('%H:%M')), class: 'form-control mask_hour', required: true %>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            <% if !@service_request.date_scheduled.nil? %>
              <%= submit_tag 'Reprogramar', class: 'btn btn-warning' %>
            <% else %>
              <%= submit_tag 'Programar', class: 'btn btn-primary' %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/service_requests/areas.js.erb
$('#area').empty().append("<%= j(options_from_collection_for_select(@areas, :id, :name)) %>");

app/views/service_requests/edit.html.erb
<h1>Editing Service Request</h1>

<%= render 'form', service_request: @service_request %>

<%= link_to 'Show', @service_request %> |
<%= link_to 'Back', service_requests_path %>

app/views/service_requests/forward_responsible.js.erb
$("#div_forward_responsible").html("<%= j(render partial: 'modal_forward_responsible', locals: {service_request_id: @service_request_id}) %>");
$("#modalForward").modal('show');

app/views/service_requests/index.html.erb
<div class="pull-right">
  <a class="btn btn-primary" href="/service_requests/new" role="button">Solicitar Serviço</a>
</div>
<span style="font-size: 30px;">Serviços</span>
<hr>
<div>
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation"><a href="#tab_area" aria-controls="tab_area" role="tab" data-toggle="tab">Área</a></li>
    <li role="presentation" class="active"><a href="#tab_attend" aria-controls="home" role="tab" data-toggle="tab">Atender</a></li>
    <li role="presentation"><a href="#tab_attended" aria-controls="tab_attended" role="tab" data-toggle="tab">Atendidos</a></li>
    <li role="presentation"><a href="#tab_requested" aria-controls="tab_requested" role="tab" data-toggle="tab">Solicitados</a></li>
  </ul>
  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane" id="tab_area">
      <%= render partial: 'area' %>
    </div>
    <div role="tabpanel" class="tab-pane active" id="tab_attend">
      <%= render partial: 'attend' %>
    </div>
    <div role="tabpanel" class="tab-pane" id="tab_attended">
      <%= render partial: 'attended' %>
    </div>
    <div role="tabpanel" class="tab-pane" id="tab_requested">
      <%= render partial: 'requested' %>
    </div>
  </div>
</div>

app/views/service_requests/new.html.erb
<div class="pull-right">
  <a class="btn btn-primary" href="/service_requests" role="button">Meus Serviços</a>
</div>
<span style="font-size: 30px;">Solicitar Serviço</span>
<hr>

<%= render 'form', service_request: @service_request %>

app/views/service_requests/schedule_request.js.erb
$("#div_schedule_request").html("<%= j(render partial: 'modal_schedule_request', locals: {service_request_id: @service_request_id}) %>");
$("#modalSchedule").modal('show');

app/views/service_requests/services_area.js.erb
$('#service').empty().append("<%= j(options_from_collection_for_select(@services_area, :id, :name)) %>");

app/views/service_requests/show.html.erb
<div class="pull-right">
  <a class="btn btn-primary" href="/service_requests" role="button">Voltar</a>
</div>
<span style="font-size: 30px;">Detalhes do Serviço</span>
<hr>

<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Informações da Solicitação</h3>
  </div>
  <div class="panel-body">
    <p>
      <strong>Data/Hora da Solicitãção:</strong>
      <%= @service_request.date_request&.strftime('%d/%m/%Y') + ' ' + @service_request.time_request&.strftime('%H:%M') %>
    </p>
    <p>
      <strong>Serviço:</strong>
      <%= @service_request.service&.name %>
    </p>
    <p>
      <strong>Descrição do Serviço:</strong>
      <%= @service_request.description_problem %>
    </p>
    <p>
      <strong>Unidade Socioeducativa:</strong>
      <%= @service_request.unit&.name %>
    </p>
    <p>
      <strong>Área Solicitante:</strong>
      <%= Area.find_by(id: @service_request.area_requesting)&.name %>
    </p>
    <p>
      <strong>Usuário Solicitante:</strong>
      <%= User.find_by(id: @service_request.user_requesting)&.name %>
    </p>
    <p>
      <strong>Serviço Solicitado para:</strong>
      <%= User.find_by(id: @service_request.service_for)&.name %>
    </p>
    <p>
      <strong>Arquivos:</strong><br>
      <% if !@list_service_files.blank? %>
        <% @list_service_files.each do |file| %>
          <ul>
            <li><%= link_to file, download_file_path(id: @service_request.id, filename: file), method: :post %></li>
          </ul>
        <% end %>
      <% end %>
    </p>
  </div>
</div>

<div class="panel panel-success">
  <div class="panel-heading">
    <h3 class="panel-title">Informações do Atendimento</h3>
  </div>
  <div class="panel-body">
    <p>
      <strong>Data da Resposta:</strong>
      <%= @service_request&.date_response %>
    </p>

    <p>
      <strong>Hora da Resposta:</strong>
      <%= @service_request&.time_response %>
    </p>

    <p>
      <strong>Data Programada:</strong>
      <%= @service_request.date_scheduled&.strftime('%d/%m/%Y') %>
    </p>

    <p>
      <strong>Hora Programada:</strong>
      <%= @service_request.time_scheduled&.strftime('%H:%M') %>
    </p>

    <p>
      <strong>Usuário Responsável pelo Atendimento:</strong>
      <%= User.find(@service_request.user_responsible_attendance)&.name if !@service_request.user_responsible_attendance.nil? %>
    </p>

    <p>
      <strong>Data Realização do Serviço:</strong>
      <%= @service_request.date_service&.strftime('%d/%m/%Y') %>
    </p>

    <p>
      <strong>Hora Realização do Serviço:</strong>
      <%= @service_request.time_service&.strftime('%H:%M') %>
    </p>

    <p>
      <strong>Tempo para Finalização do Serviço:</strong>
      <%= @service_request.time_finalization_attendance %>
    </p>

    <p>
      <strong>Observações:</strong>
      <%= @service_request.notes %>
    </p>

    <p>
      <strong>Status:</strong>
      <%= @service_request&.status&.description %>
    </p>

    <p>
      <strong>Tempo Máximo para Atendimento:</strong>
      <%= @service_request.maximum_time_of_attendance %>
    </p>
  </div>
</div>

app/views/service_requests/subareas.js.erb
$('#subarea').empty().append("<%= j(options_from_collection_for_select(@subareas, :id, :name)) %>");