config/routes.rb
Rails.application.routes.draw do
  resources :user_areas
  resources :services
  resources :service_requests do
    collection do
      post :areas
      post :subareas
      match :services_area, via: [:get, :post]
      get :answer_request
      get :schedule_request
      get :forward_responsible
      post :save_forward_responsible
      post :save_schedule_request
      post :save_answer_service
    end
  end
  post 'services_area' => 'service_requests#services_area'
  post 'download_file' => 'service_requests#download_file'

  resources :units
  resources :areas
  get 'dashboard/index'
  # patch "process_managers/update" => "process_managers#update", :as => "process_managers/update"
  resources :process_managers do
    collection do
      post :search_process
  	end
  end
  devise_for :users, controllers: { sessions: 'users/sessions' }
  get 'home/index'
  root to: 'dashboard#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
	has_many :user_areas
	belongs_to :unit
end

app/models/priority.rb
class Priority < ApplicationRecord
end

app/models/process_manager.rb
class ProcessManager < ApplicationRecord
	validates :process_number, :opening_hour_date, :subject, :notes, :confidentiality_level, :priority, :authors, presence: true
end

app/models/service.rb
class Service < ApplicationRecord
	has_many :service_requests
end

app/models/service_file.rb
class ServiceFile < ApplicationRecord

	def self.upload_file(files, directory)
		FileUtils.mkdir(directory) unless File.exists?(directory)
		if !files.nil?
			files.each do |file|
				File.open(File.join(directory, file.original_filename), 'wb') { |f| f.write(file.read) }
			end
		end
	end

	def self.download_file(directory)
		send_file directory
	end

	def self.list_service_files(service_id)
		directory = ServiceRequest.find(service_id).files_directory
		if !directory.nil?
			files = Dir.foreach(directory).map { |f| File.basename("#{f}") }.tap { |x| x.delete(".."); x.delete("."); }
		end
	end

end

app/models/service_request.rb
class ServiceRequest < ApplicationRecord
  belongs_to :unit, required: false
  belongs_to :status, required: false
  belongs_to :service
end

app/models/status.rb
class Status < ApplicationRecord
end

app/models/unit.rb
class Unit < ApplicationRecord
	has_many :areas
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true
  has_many :user_areas
  has_many :areas, through: :user_areas
end

app/models/user_area.rb
class UserArea < ApplicationRecord
  belongs_to :user
  belongs_to :area
end

app/models/viproc_information.rb
class ViprocInformation < ApplicationRecord
	require 'savon'

	HOMOLOGACAO = 'http://viprocwsejb-h.seplag.ce.gov.br/viprocws/ViprocService?wsdl'
	# PRODUCAO = 'http://viprocwsejb.seplag.ce.gov.br/viprocws/ViprocService?wsdl'

	CLIENT = Savon.client(element_form_default: :unspecified, wsdl: HOMOLOGACAO)

	def self.criar_processo(parametros)
		CLIENT.call(:criar_processo, message: parametros)
	end

	def self.listar_assuntos
		CLIENT.call(:listar_assuntos).body[:listar_assuntos_response][:return].sort
	end

	def self.listar_sigla_orgaos
		CLIENT.call(:listar_sigla_orgaos).body[:listar_sigla_orgaos_response][:return].sort
	end

	def self.listar_sigla_lotacoes
		CLIENT.call(:listar_sigla_lotacoes)
	end

end

app/models/viproc_profile.rb
class ViprocProfile < ApplicationRecord
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url, notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:name, :active)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@process_manager = ProcessManager.new
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  # GET /units
  # GET /units.json
  def index
    @units = Unit.all
  end

  # GET /units/1
  # GET /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url, notice: 'Unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:name, :address, :address_number, :add_address, :active)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/user_areas_helper.rb
module UserAreasHelper
end

app/views/areas/_form.html.erb
<%= form_with(model: area, local: true) do |form| %>
  <% if area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(area.errors.count, "error") %> prohibited this area from being saved:</h2>

      <ul>
      <% area.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :area_name %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active, id: :area_active %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/areas/edit.html.erb
<h1>Editing Area</h1>

<%= render 'form', area: @area %>

<%= link_to 'Show', @area %> |
<%= link_to 'Back', areas_path %>

app/views/areas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Areas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @areas.each do |area| %>
      <tr>
        <td><%= area.name %></td>
        <td><%= area.active %></td>
        <td><%= link_to 'Show', area %></td>
        <td><%= link_to 'Edit', edit_area_path(area) %></td>
        <td><%= link_to 'Destroy', area, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Area', new_area_path %>

app/views/areas/new.html.erb
<h1>New Area</h1>

<%= render 'form', area: @area %>

<%= link_to 'Back', areas_path %>

app/views/areas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @area.name %>
</p>

<p>
  <strong>Active:</strong>
  <%= @area.active %>
</p>

<%= link_to 'Edit', edit_area_path(@area) %> |
<%= link_to 'Back', areas_path %>

app/views/units/_form.html.erb
<%= form_with(model: unit, local: true) do |form| %>
  <% if unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
      <% unit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :unit_name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :unit_address %>
  </div>

  <div class="field">
    <%= form.label :address_number %>
    <%= form.number_field :address_number, id: :unit_address_number %>
  </div>

  <div class="field">
    <%= form.label :add_address %>
    <%= form.text_field :add_address, id: :unit_add_address %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active, id: :unit_active %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/units/edit.html.erb
<h1>Editing Unit</h1>

<%= render 'form', unit: @unit %>

<%= link_to 'Show', @unit %> |
<%= link_to 'Back', units_path %>

app/views/units/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Units</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Address number</th>
      <th>Add address</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @units.each do |unit| %>
      <tr>
        <td><%= unit.name %></td>
        <td><%= unit.address %></td>
        <td><%= unit.address_number %></td>
        <td><%= unit.add_address %></td>
        <td><%= unit.active %></td>
        <td><%= link_to 'Show', unit %></td>
        <td><%= link_to 'Edit', edit_unit_path(unit) %></td>
        <td><%= link_to 'Destroy', unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Unit', new_unit_path %>

app/views/units/new.html.erb
<h1>New Unit</h1>

<%= render 'form', unit: @unit %>

<%= link_to 'Back', units_path %>

app/views/units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @unit.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @unit.address %>
</p>

<p>
  <strong>Address number:</strong>
  <%= @unit.address_number %>
</p>

<p>
  <strong>Add address:</strong>
  <%= @unit.add_address %>
</p>

<p>
  <strong>Active:</strong>
  <%= @unit.active %>
</p>

<%= link_to 'Edit', edit_unit_path(@unit) %> |
<%= link_to 'Back', units_path %>