config/routes.rb
Rails.application.routes.draw do
  resources :user_areas
  resources :services
  resources :service_requests do
    collection do
      post :areas
      post :subareas
      match :services_area, via: [:get, :post]
      get :answer_request
      get :schedule_request
      get :forward_responsible
      post :save_forward_responsible
      post :save_schedule_request
      post :save_answer_service
    end
  end
  post 'services_area' => 'service_requests#services_area'
  post 'download_file' => 'service_requests#download_file'

  resources :units
  resources :areas
  get 'dashboard/index'
  # patch "process_managers/update" => "process_managers#update", :as => "process_managers/update"
  resources :process_managers do
    collection do
      post :search_process
  	end
  end
  devise_for :users, controllers: { sessions: 'users/sessions' }
  get 'home/index'
  root to: 'dashboard#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
	has_many :user_areas
	belongs_to :unit
end

app/models/priority.rb
class Priority < ApplicationRecord
end

app/models/process_manager.rb
class ProcessManager < ApplicationRecord
	validates :process_number, :opening_hour_date, :subject, :notes, :confidentiality_level, :priority, :authors, presence: true
end

app/models/service.rb
class Service < ApplicationRecord
	has_many :service_requests
end

app/models/service_file.rb
class ServiceFile < ApplicationRecord

	def self.upload_file(files, directory)
		FileUtils.mkdir(directory) unless File.exists?(directory)
		if !files.nil?
			files.each do |file|
				File.open(File.join(directory, file.original_filename), 'wb') { |f| f.write(file.read) }
			end
		end
	end

	def self.download_file(directory)
		send_file directory
	end

	def self.list_service_files(service_id)
		directory = ServiceRequest.find(service_id).files_directory
		if !directory.nil?
			files = Dir.foreach(directory).map { |f| File.basename("#{f}") }.tap { |x| x.delete(".."); x.delete("."); }
		end
	end

end

app/models/service_request.rb
class ServiceRequest < ApplicationRecord
  belongs_to :unit, required: false
  belongs_to :status, required: false
  belongs_to :service
end

app/models/status.rb
class Status < ApplicationRecord
end

app/models/unit.rb
class Unit < ApplicationRecord
	has_many :areas
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true
  has_many :user_areas
  has_many :areas, through: :user_areas
end

app/models/user_area.rb
class UserArea < ApplicationRecord
  belongs_to :user
  belongs_to :area
end

app/models/viproc_information.rb
class ViprocInformation < ApplicationRecord
	require 'savon'

	HOMOLOGACAO = 'http://viprocwsejb-h.seplag.ce.gov.br/viprocws/ViprocService?wsdl'
	# PRODUCAO = 'http://viprocwsejb.seplag.ce.gov.br/viprocws/ViprocService?wsdl'

	CLIENT = Savon.client(element_form_default: :unspecified, wsdl: HOMOLOGACAO)

	def self.criar_processo(parametros)
		CLIENT.call(:criar_processo, message: parametros)
	end

	def self.listar_assuntos
		CLIENT.call(:listar_assuntos).body[:listar_assuntos_response][:return].sort
	end

	def self.listar_sigla_orgaos
		CLIENT.call(:listar_sigla_orgaos).body[:listar_sigla_orgaos_response][:return].sort
	end

	def self.listar_sigla_lotacoes
		CLIENT.call(:listar_sigla_lotacoes)
	end

end

app/models/viproc_profile.rb
class ViprocProfile < ApplicationRecord
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@process_manager = ProcessManager.new
  end
end

app/controllers/process_managers_controller.rb
class ProcessManagersController < ApplicationController
  before_action :set_process_manager, only: [:show, :edit, :update, :destroy]

  # GET /process_managers
  # GET /process_managers.json
  def index
    @process_managers = ProcessManager.all
  end

  # GET /process_managers/1
  # GET /process_managers/1.json
  def show
  end

  # GET /process_managers/new
  def new
    @process_manager = ProcessManager.new
  end

  # GET /process_managers/1/edit
  def edit
  end

  # POST /process_managers
  # POST /process_managers.json
  def create
    @process_manager = ProcessManager.new(process_manager_params)
    @process_manager.key_words = params[:key_words]
    @process_manager.authors = params[:author]
    @process_manager.favored = params[:favored]

    # respond_to do |format|
      if @process_manager.save
        flash[:notice] = 'Processo incluido com sucesso.'
        redirect_to controller: :home, action: :index
        # format.html { redirect_to @process_manager, notice: 'Process manager was successfully created.' }
        # format.json { render :show, status: :created, location: @process_manager }
      else
        format.html { render :new }
        format.json { render json: @process_manager.errors, status: :unprocessable_entity }
      end
    # end
  end

  # PATCH/PUT /process_managers/1
  # PATCH/PUT /process_managers/1.json
  def update
    # respond_to do |format|
      if @process_manager.update(process_manager_params)
        @process_manager.key_words = params[:key_words]
        @process_manager.authors = params[:author]
        @process_manager.favored = params[:favored]
        @process_manager.save

        redirect_to action: :new
        # format.html { redirect_to @process_manager, notice: 'Process manager was successfully updated.' }
        # format.json { render :show, status: :ok, location: @process_manager }
      else
        format.html { render :edit }
        format.json { render json: @process_manager.errors, status: :unprocessable_entity }
      end
    # end
  end

  # DELETE /process_managers/1
  # DELETE /process_managers/1.json
  def destroy
    @process_manager.destroy
    respond_to do |format|
      format.html { redirect_to process_managers_url, notice: 'Process manager was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search_process
    @process_manager = ProcessManager.find_by_process_number(params[:process_number])

    redirect_to '/process_managers/'+@process_manager.id.to_s+'/edit'
    # render partial: 'form', locals: { process_manager: @process_manager }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_process_manager
      @process_manager = ProcessManager.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def process_manager_params
      params.require(:process_manager).permit(:process_number, :opening_hour_date, :subject, :notes, :key_words, :confidentiality_level, :priority, :created_by, :status, :deadline, :authors, :favored)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/process_managers_helper.rb
module ProcessManagersHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/user_areas_helper.rb
module UserAreasHelper
end

app/views/process_managers/_form.html.erb
<div>
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#process" aria-controls="Process" role="tab" data-toggle="tab" class="text-uppercase">Processos</a></li>
    <li role="presentation"><a href="#tramitacao" aria-controls="tramitacao" role="tab" data-toggle="tab" class="text-uppercase">Tramitações</a></li>
  </ul>
  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="process"><br>
      <%= form_with(model: @process_manager, local: true, id: 'form') do |form| -%>
        <% if process_manager.new_record? %>
          <nav class="navbar navbar-default">
            <ul class="nav navbar-nav navProcess">
              <li class="text-uppercase"><%= link_to 'Incluir', "#", :onclick=>"$('#form').submit()" %></li>
              <li class="text-uppercase"><%= link_to "Limpar", '#', onclick: 'clear_form()' %></li>
            </ul>
          </nav>
        <% else %>
          <nav class="navbar navbar-default">
            <ul class="nav navbar-nav navProcess">
              <li class="text-uppercase"><%= link_to 'Atualizar', "#", :onclick => "$('#form').submit()" %></li>
              <li class="text-uppercase"><%= link_to 'Novo', home_index_path %></li>
            </ul>
          </nav>
        <% end %>
        <!-- <br>
        <%# if !flash[:notice].blank? %>
          <div class="alert alert-success" role="alert">
            <%#= flash[:notice] %>
          </div>
        <%# end -%>
        <%# if process_manager.errors.any? %>
          <div id="error_explanation">
            <h2>
              <%#= pluralize(process_manager.errors.count, "error") %> prohibited this process_manager from being saved:
            </h2>

            <ul>
              <%# process_manager.errors.full_messages.each do |message| %>
                <li>
                  <%#= message %>
                </li>
              <%# end %>
            </ul>
          </div>
        <%# end %> -->
        <section class="container-fluid">
          <div class="row">
            <div class="col-md-2">
              <%= form.label :process_number %><br>
              <%= form.text_field :process_number, id: :process_manager_process_number, class: 'form-control mask_process' %>
              <%# form.text_field :process_number, id: :process_manager_process_number, value: Time.current.strftime('%d%m%Y%H%M'), readonly: true, class: 'form-control' %>
            </div>

            <div class="col-md-2">
              <%= form.label :opening_hour_date %>
              <% if process_manager.new_record? %>
                <%= form.text_field :opening_hour_date, id: :process_manager_opening_hour_date, value: Time.current.strftime('%d/%m/%Y %H:%M'), readonly: true, class: 'form-control' %>
              <% else %>
                <%= form.text_field :opening_hour_date, id: :process_manager_opening_hour_date, readonly: true, class: 'form-control' %>
              <% end %>
            </div>
            
            <div class="col-md-3">
              <%= form.label :confidentiality_level %><b style="color: red;"> *</b><br>
              <%= form.collection_select :confidentiality_level, ConfidentialityLevel.all, :id, :description, {prompt: 'Selecione'}, {class: 'form-control'} %>
            </div>

            <div class="col-md-3">
              <%= form.label :priority %><b style="color: red;"> *</b><br>
              <%= form.collection_select :priority, Priority.all, :id, :description, {prompt: 'Selecione'}, {class: 'form-control'} %>
            </div>

            <div class="col-md-2">
              <%= form.label :deadline %><br>
              <%= form.text_field :deadline, class: 'datepicker form-control' %>
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-md-12">
              <%= form.label :subject %><b style="color: red;"> *</b><br>
              <%= form.select :subject, ViprocInformation.listar_assuntos, {prompt: 'Selecione', required: true}, class: 'form-control select2' %>
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-md-6">
              <%= form.label :notes %><b style="color: red;"> *</b><br>
              <%= form.text_area :notes, id: :process_manager_notes, required: true, class: 'form-control' %>
            </div>
            <div class="col-md-6">
              <%= form.label :key_words %><b style="color: red;"> *</b><br>
              <% if process_manager.new_record? %>
                <%= select_tag :key_words, options_for_select([]), {multiple: true, class: 'form-control select2-tag'} %>
              <% else %>
                <%= select_tag :key_words, options_for_select(process_manager.key_words, selected: process_manager.key_words), {multiple: true, class: 'form-control select2-tag'} %>
              <% end %>
            </div>
          </div>
          <br>
          <%= form.hidden_field :created_by, id: :process_manager_created_by, value: current_user.id %>
          <div class="row">
            <div class="col-md-6">
              <label>Autores do Processo</label>
              <% if process_manager.new_record? %>
                <%= select_tag :author, options_for_select(ViprocInformation.listar_sigla_orgaos), {multiple: true, class: 'form-control select2-tag'} %>
              <% else %>
                <%= select_tag :author, options_for_select(ViprocInformation.listar_sigla_orgaos, selected: process_manager.authors), {multiple: true, class: 'form-control select2-tag'} %>
              <% end %>
            </div>
            <div class="col-md-6">
              <label>Favorecidos do Processo</label>
              <% if process_manager.new_record? %>
                <%= select_tag :favored, options_for_select(ViprocInformation.listar_sigla_orgaos), {multiple: true, class: 'form-control select2-tag clear'} %>
              <% else %>
                <%= select_tag :favored, options_for_select(ViprocInformation.listar_sigla_orgaos, selected: process_manager.favored), {multiple: true, class: 'form-control select2-tag clear'} %>
              <% end %>
            </div>
          </div>
          <br>
        </section>
      <% end %>
    </div>
    <div role="tabpanel" class="tab-pane" id="tramitacao">
      <br>
      <form class="form-horizontal">
        <div class="form-group">
          <div class="col-md-12">
            <label class="control-label" for="textarea">Ultimas observações enviadas</label>
            <textarea class="form-control" id="textarea" name="textarea"></textarea>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-8">
            <div class="dropdown">
              <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="true">
                  Responsavel Atual
                  <span class="caret"></span>
                </button>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                <li><a href="#">Option</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div>
          <!-- <button type="button" class="btn btn-default">Tramitar</button>
          <button type="button" class="btn btn-default">Alterar fase</button>
          <button type="button" class="btn btn-default"> Alerta situação</button>
          <button type="button" class="btn btn-default">Cadastrais</button> -->
          <button type="button" class="btn btn-default">Excluir</button>
          <!-- <button type="button" class="btn btn-default">Comprovante de envio</button> -->
        </div>
        <hr>
        <div class="panel panel-default">
          <div class="panel-heading text-uppercase text-center">
            Tramitações
          </div>
          <table class="table table-bordered">
            <tr class="success">
              <td><b>Orgão</b></td>
              <td><b>Localização</b></td>
              <td><b>Informações</b></td>
              <td><b>Fase</b></td>
              <td><b>Situação</b></td>
              <td><b>Permanência</b></td>
              <td><b>Data/Hora</b></td>
            </tr>
            <tr>
              <td>SEAS</td>
              <td>Celula de tecnologia da Informação</td>
              <td>1 | 2 | 4 | 3</td>
              <td>Para providências</td>
              <td>Aguardando providências</td>
              <td>0 min</td>
              <td>00/00/000 10:30</td>
            </tr>
            <tr>
              <td>SEAS</td>
              <td>Celula de tecnologia da Informação</td>
              <td>1 | 2 | 4 | 3</td>
              <td>Para providências</td>
              <td>Aguardando providências</td>
              <td>0 min</td>
              <td>00/00/000 10:30</td>
            </tr>
            <tr>
              <td>SEAS</td>
              <td>Celula de tecnologia da Informação</td>
              <td>1 | 2 | 4 | 3</td>
              <td>Para providências</td>
              <td>Aguardando providências</td>
              <td>0 min</td>
              <td>00/00/000 10:30</td>
            </tr>
          </table>
        </div>
      </form>
    </div>
  </div>
</div>

app/views/process_managers/edit.html.erb
<%= render 'form', process_manager: @process_manager %>

app/views/process_managers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Process Managers</h1>

<table>
  <thead>
    <tr>
      <th>Process number</th>
      <th>Opening hour date</th>
      <th>Subject</th>
      <th>Notes</th>
      <th>Key words</th>
      <th>Confidentiality level</th>
      <th>Priority</th>
      <th>Created by</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @process_managers.each do |process_manager| %>
      <tr>
        <td><%= process_manager.process_number %></td>
        <td><%= process_manager.opening_hour_date %></td>
        <td><%= process_manager.subject %></td>
        <td><%= process_manager.notes %></td>
        <td><%= process_manager.key_words %></td>
        <td><%= process_manager.confidentiality_level %></td>
        <td><%= process_manager.priority %></td>
        <td><%= process_manager.created_by %></td>
        <td><%= process_manager.status %></td>
        <td><%= link_to 'Show', process_manager %></td>
        <td><%= link_to 'Edit', edit_process_manager_path(process_manager) %></td>
        <td><%= link_to 'Destroy', process_manager, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Process Manager', new_process_manager_path %>

app/views/process_managers/new.html.erb
<div class="container-fluid">
	<h3>Incluir Processo</h3>
	<%= render 'form', process_manager: @process_manager %>
	<%#= link_to 'Back', process_managers_path %>
</div>

app/views/process_managers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Process number:</strong>
  <%= @process_manager.process_number %>
</p>

<p>
  <strong>Opening hour date:</strong>
  <%= @process_manager.opening_hour_date %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @process_manager.subject %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @process_manager.notes %>
</p>

<p>
  <strong>Key words:</strong>
  <%= @process_manager.key_words %>
</p>

<p>
  <strong>Confidentiality level:</strong>
  <%= @process_manager.confidentiality_level %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @process_manager.priority %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @process_manager.created_by %>
</p>

<p>
  <strong>Status:</strong>
  <%= @process_manager.status %>
</p>

<%= link_to 'Edit', edit_process_manager_path(@process_manager) %> |
<%= link_to 'Back', process_managers_path %>